export const data = [
  {
    id: 1,
    member: "카리나",
    memberPhoto: "karina.jpeg",
    realname: "유지민",
    birth: "2000년 4월 11일",
    position: "리더, 메인댄서",
    skill: "Rocket Puncher",
    sns: "https://www.instagram.com/katarinabluu/",
  },
  {
    id: 2,
    member: "윈터",
    memberPhoto: "winter.jpeg",
    realname: "김민정",
    birth: "2001년 1월 1일",
    position: "메인보컬",
    skill: "Armamenter",
    sns: "https://www.instagram.com/imwinter/",
  },
  {
    id: 3,
    member: "지젤",
    memberPhoto: "gizelle.jpeg",
    realname: "김애리",
    birth: "2000년 10월 30일",
    position: "서브보컬",
    skill: "Xenoglossy",
    sns: "https://www.instagram.com/aerichandesu/",
  },
  {
    id: 4,
    member: "닝닝",
    memberPhoto: "ningning.jpeg",
    realname: "宁艺卓(닝이줘)",
    birth: "2002년 10월 23일",
    position: "리더",
    skill: "E.D Hacker",
    sns: "https://www.instagram.com/imnotningning/",
  },
];
